import axios from "axios";

const userData = [
  { email: "ramu1@gmail.com", name: "Ramu Kumar", username: "ramuKumar1", password: "password1" },
  { email: "rakesh1@gmail.com", name: "Rakesh Sharma", username: "rakeshSharma1", password: "password2" },
  { email: "monu1@gmail.com", name: "Monu Singh", username: "monuSingh2", password: "password3" },
  { email: "harshu1@gmail.com", name: "Harshu Yadav", username: "harshuYadav3", password: "password4" },
  { email: "rajesh1@gmail.com", name: "Rajesh Gupta", username: "rajeshGupta1", password: "password5" },
  { email: "ramesh1@gmail.com", name: "Ramesh Iyer", username: "rameshIyer2", password: "password6" },
  { email: "jekky1@gmail.com", name: "Jekky Patel", username: "jekkyPatel3", password: "password7" },
  { email: "solemon1@gmail.com", name: "Solemon Roy", username: "solemonRoy1", password: "password8" },
  { email: "shurbhi1@gmail.com", name: "Shurbhi Verma", username: "shurbhiVerma2", password: "password9" },
  { email: "gungun1@gmail.com", name: "Gungun Chaudhary", username: "gungunChaudhary3", password: "password10" },
  { email: "mohan1@gmail.com", name: "Mohan Nair", username: "mohanNair4", password: "password11" },
  { email: "john1@example.com", name: "John Doe", username: "johnDoe5", password: "password12" },
  { email: "jane1@example.com", name: "Jane Smith", username: "janeSmith6", password: "password13" },
  { email: "alice1@example.com", name: "Alice Johnson", username: "aliceJohnson7", password: "password14" },
  { email: "bob1@example.com", name: "Bob Brown", username: "bobBrown8", password: "password15" },
  { email: "carol1@example.com", name: "Carol White", username: "carolWhite9", password: "password16" },
  { email: "dave1@example.com", name: "Dave Wilson", username: "daveWilson10", password: "password17" },
  { email: "edward1@example.com", name: "Edward Thomas", username: "edwardThomas11", password: "password18" },
  { email: "fiona1@example.com", name: "Fiona Taylor", username: "fionaTaylor12", password: "password19" },
  { email: "george1@example.com", name: "George Miller", username: "georgeMiller13", password: "password20" },
  { email: "harry1@example.com", name: "Harry Davis", username: "harryDavis14", password: "password21" },
  { email: "irene1@example.com", name: "Irene Garcia", username: "ireneGarcia15", password: "password22" },
  { email: "jack1@example.com", name: "Jack Rodriguez", username: "jackRodriguez16", password: "password23" },
  { email: "kim1@example.com", name: "Kim Martinez", username: "kimMartinez17", password: "password24" },
  { email: "lisa1@example.com", name: "Lisa Hernandez", username: "lisaHernandez18", password: "password25" },
  { email: "mike1@example.com", name: "Mike Lopez", username: "mikeLopez19", password: "password26" },
  { email: "nina1@example.com", name: "Nina Clark", username: "ninaClark20", password: "password27" },
  { email: "olivia1@example.com", name: "Olivia Lewis", username: "oliviaLewis21", password: "password28" },
  { email: "paul1@example.com", name: "Paul Lee", username: "paulLee22", password: "password29" },
  { email: "quinn1@example.com", name: "Quinn Walker", username: "quinnWalker23", password: "password30" },
  { email: "rachel1@example.com", name: "Rachel Hall", username: "rachelHall24", password: "password31" },
  { email: "sarah1@example.com", name: "Sarah Allen", username: "sarahAllen25", password: "password32" },
  { email: "tony1@example.com", name: "Tony Young", username: "tonyYoung26", password: "password33" },
  { email: "uma1@example.com", name: "Uma King", username: "umaKing27", password: "password34" },
  { email: "victor1@example.com", name: "Victor Wright", username: "victorWright28", password: "password35" },
  { email: "winnie1@example.com", name: "Winnie Scott", username: "winnieScott29", password: "password36" },
  { email: "xander1@example.com", name: "Xander Hill", username: "xanderHill30", password: "password37" },
  { email: "yara1@gmail.com", name: "Yara Green", username: "yaraGreen31", password: "password38" },
  { email: "zane1@gmail.com", name: "Zane Adams", username: "zaneAdams32", password: "password39" },
  { email: "aaron1@example.com", name: "Aaron Baker", username: "aaronBaker33", password: "password40" },
  { email: "bella1@example.com", name: "Bella Carter", username: "bellaCarter34", password: "password41" },
  { email: "clara1@example.com", name: "Clara Perez", username: "claraPerez35", password: "password42" },
  { email: "diana1@example.com", name: "Diana Roberts", username: "dianaRoberts36", password: "password43" },
  { email: "ella1@example.com", name: "Ella Turner", username: "ellaTurner37", password: "password44" },
  { email: "frank1@example.com", name: "Frank Phillips", username: "frankPhillips38", password: "password45" },
  { email: "grace1@example.com", name: "Grace Campbell", username: "graceCampbell39", password: "password46" },
  { email: "hannah1@example.com", name: "Hannah Mitchell", username: "hannahMitchell40", password: "password47" },
  { email: "ian1@example.com", name: "Ian Edwards", username: "ianEdwards41", password: "password48" },
  { email: "jake1@example.com", name: "Jake Turner", username: "jakeTurner42", password: "password49" },
  { email: "kira1@example.com", name: "Kira Simmons", username: "kiraSimmons43", password: "password50" },
  { email: "leo1@example.com", name: "Leo Murphy", username: "leoMurphy44", password: "password51" },
  { email: "mia1@example.com", name: "Mia Foster", username: "miaFoster45", password: "password52" },
  { email: "noah1@example.com", name: "Noah Reed", username: "noahReed46", password: "password53" },
  { email: "oliver1@example.com", name: "Oliver Powell", username: "oliverPowell47", password: "password54" },
  { email: "paige1@example.com", name: "Paige Long", username: "paigeLong48", password: "password55" },
  { email: "quincy1@example.com", name: "Quincy Price", username: "quincyPrice49", password: "password56" },
  { email: "ruby1@example.com", name: "Ruby Fisher", username: "rubyFisher50", password: "password57" },
  { email: "sophie1@example.com", name: "Sophie Johnson", username: "sophieJohnson51", password: "password58" },
  { email: "tyler1@example.com", name: "Tyler Turner", username: "tylerTurner52", password: "password59" },
  { email: "uma2@example.com", name: "Uma King", username: "umaKing53", password: "password60" },
  { email: "vance1@example.com", name: "Vance Campbell", username: "vanceCampbell54", password: "password61" },
  { email: "wally1@example.com", name: "Wally Harris", username: "wallyHarris55", password: "password62" },
  { email: "xena1@example.com", name: "Xena Brooks", username: "xenaBrooks56", password: "password63" },
  { email: "yasmine1@example.com", name: "Yasmine Cooper", username: "yasmineCooper57", password: "password64" },
  { email: "zach1@example.com", name: "Zachary Diaz", username: "zacharyDiaz58", password: "password65" },
  { email: "alina1@example.com", name: "Alina Wood", username: "alinaWood59", password: "password66" },
  { email: "benny1@example.com", name: "Benny Rogers", username: "bennyRogers60", password: "password67" },
  { email: "cecil1@example.com", name: "Cecilia Reed", username: "ceciliaReed61", password: "password68" },
  { email: "dean1@example.com", name: "Dean Sanders", username: "deanSanders62", password: "password69" },
  { email: "ella2@example.com", name: "Ella Perry", username: "ellaPerry63", password: "password70" },
  { email: "felix1@example.com", name: "Felix Price", username: "felixPrice64", password: "password71" },
  { email: "gwen1@example.com", name: "Gwen Hughes", username: "gwenHughes65", password: "password72" },
  { email: "harper1@example.com", name: "Harper Kelly", username: "harperKelly66", password: "password73" },
  { email: "isaac1@example.com", name: "Isaac Bell", username: "isaacBell67", password: "password74" },
  { email: "jasmine1@example.com", name: "Jasmine Ward", username: "jasmineWard68", password: "password75" },
  { email: "kendra1@example.com", name: "Kendra Flores", username: "kendraFlores69", password: "password76" },
  { email: "larry1@example.com", name: "Larry Brooks", username: "larryBrooks70", password: "password77" },
  { email: "marie1@example.com", name: "Marie Ross", username: "marieRoss71", password: "password78" },
  { email: "natalie1@example.com", name: "Natalie Bell", username: "natalieBell72", password: "password79" },
  { email: "owen1@example.com", name: "Owen Wood", username: "owenWood73", password: "password80" },
  { email: "penny1@example.com", name: "Penny Young", username: "pennyYoung74", password: "password81" },
  { email: "quade1@example.com", name: "Quade Butler", username: "quadeButler75", password: "password82" },
  { email: "rayna1@example.com", name: "Rayna Hall", username: "raynaHall76", password: "password83" },
  { email: "sampson1@example.com", name: "Sampson Reed", username: "sampsonReed77", password: "password84" },
  { email: "tiffany1@example.com", name: "Tiffany Moore", username: "tiffanyMoore78", password: "password85" },
  { email: "ursula1@example.com", name: "Ursula Jackson", username: "ursulaJackson79", password: "password86" },
  { email: "vlad1@example.com", name: "Vlad Ramirez", username: "vladRamirez80", password: "password87" },
  { email: "wade1@example.com", name: "Wade Parker", username: "wadeParker81", password: "password88" },
  { email: "xander2@example.com", name: "Xander Mitchell", username: "xanderMitchell82", password: "password89" },
  { email: "yuna1@example.com", name: "Yuna Coleman", username: "yunaColeman83", password: "password90" },
  { email: "zara1@example.com", name: "Zara Bennett", username: "zaraBennett84", password: "password91" },
  { email: "ashley1@example.com", name: "Ashley Cruz", username: "ashleyCruz85", password: "password92" },
  { email: "benjamin1@example.com", name: "Benjamin Diaz", username: "benjaminDiaz86", password: "password93" },
  { email: "chloe1@example.com", name: "Chloe Rivera", username: "chloeRivera87", password: "password94" },
  { email: "daniel1@example.com", name: "Daniel Cook", username: "danielCook88", password: "password95" },
  { email: "ella3@example.com", name: "Ella Murphy", username: "ellaMurphy89", password: "password96" },
  { email: "felicia1@example.com", name: "Felicia Cooper", username: "feliciaCooper90", password: "password97" },
  { email: "garrett1@example.com", name: "Garrett Edwards", username: "garrettEdwards91", password: "password98" },
  { email: "hilda1@example.com", name: "Hilda Bennett", username: "hildaBennett92", password: "password99" },
  { email: "ivan1@example.com", name: "Ivan Foster", username: "ivanFoster93", password: "password100" },
  { email: "jody1@example.com", name: "Jody Hughes", username: "jodyHughes94", password: "password101" },
  { email: "karl1@example.com", name: "Karl Sanchez", username: "karlSanchez95", password: "password102" },
  { email: "luna1@example.com", name: "Luna Morales", username: "lunaMorales96", password: "password103" },
  { email: "milo1@example.com", name: "Milo Campbell", username: "miloCampbell97", password: "password104" },
  { email: "nina2@example.com", name: "Nina Price", username: "ninaPrice98", password: "password105" },
  { email: "oscar1@example.com", name: "Oscar Diaz", username: "oscarDiaz99", password: "password106" },
  { email: "paulina1@example.com", name: "Paulina Torres", username: "paulinaTorres100", password: "password107" },
  { email: "quinton1@example.com", name: "Quinton Brooks", username: "quintonBrooks101", password: "password108" },
  { email: "renee1@example.com", name: "Renee Lee", username: "reneeLee102", password: "password109" },
  { email: "sean1@example.com", name: "Sean Evans", username: "seanEvans103", password: "password110" },
  { email: "talia1@example.com", name: "Talia Rodriguez", username: "taliaRodriguez104", password: "password111" },
  { email: "usman1@example.com", name: "Usman Williams", username: "usmanWilliams105", password: "password112" },
  { email: "veronica1@example.com", name: "Veronica Wilson", username: "veronicaWilson106", password: "password113" },
  { email: "walter1@example.com", name: "Walter Sanders", username: "walterSanders107", password: "password114" },
  { email: "xena2@example.com", name: "Xena Parker", username: "xenaParker108", password: "password115" },
  { email: "yosef1@example.com", name: "Yosef Bailey", username: "yosefBailey109", password: "password116" },
  { email: "zoe1@example.com", name: "Zoe Price", username: "zoePrice110", password: "password117" },
  { email: "albert1@example.com", name: "Albert Kelly", username: "albertKelly111", password: "password118" },
  { email: "brittany1@example.com", name: "Brittany Johnson", username: "brittanyJohnson112", password: "password119" },
  { email: "chase1@example.com", name: "Chase Collins", username: "chaseCollins113", password: "password120" },
  { email: "dahlia1@example.com", name: "Dahlia Long", username: "dahliaLong114", password: "password121" },
  { email: "evan1@example.com", name:"Evan Scott", username: "evanScott115", password: "password122" },
  { email: "farrah1@example.com", name: "Farrah Phillips", username: "farrahPhillips116", password: "password123" },
  { email: "george1@example.com", name: "George Rivera", username: "georgeRivera117", password: "password124" },
  { email: "helen1@example.com", name: "Helen Martin", username: "helenMartin118", password: "password125" },
  { email: "isaiah1@example.com", name: "Isaiah Hall", username: "isaiahHall119", password: "password126" },
  { email: "joseph1@example.com", name: "Joseph Adams", username: "josephAdams120", password: "password127" },
  { email: "keira1@example.com", name: "Keira Davis", username: "keiraDavis121", password: "password128" },
  { email: "lila1@example.com", name: "Lila Murphy", username: "lilaMurphy122", password: "password129" },
  { email: "maddox1@example.com", name: "Maddox Hughes", username: "maddoxHughes123", password: "password130" },
  { email: "nash1@example.com", name: "Nash Torres", username: "nashTorres124", password: "password131" },
  { email: "olivia1@example.com", name: "Olivia Collins", username: "oliviaCollins125", password: "password132" },
  { email: "piper1@example.com", name: "Piper Jenkins", username: "piperJenkins126", password: "password133" },
  { email: "quinn1@example.com", name: "Quinn Bell", username: "quinnBell127", password: "password134" },
  { email: "reuben1@example.com", name: "Reuben Young", username: "reubenYoung128", password: "password135" },
  { email: "sara1@example.com", name: "Sara Lee", username: "saraLee129", password: "password136" },
  { email: "tyson1@example.com", name: "Tyson Hall", username: "tysonHall130", password: "password137" },
  { email: "vicky1@example.com", name: "Vicky White", username: "vickyWhite131", password: "password138" },
  { email: "willa1@example.com", name: "Willa Jones", username: "willaJones132", password: "password139" },
  { email: "xavier1@example.com", name: "Xavier Thompson", username: "xavierThompson133", password: "password140" },
  { email: "yara1@example.com", name: "Yara Lopez", username: "yaraLopez134", password: "password141" },
  { email: "zane1@example.com", name: "Zane Campbell", username: "zaneCampbell135", password: "password142" },
  { email: "abby1@example.com", name: "Abby Lee", username: "abbyLee136", password: "password143" },
  { email: "bobby1@example.com", name: "Bobby Foster", username: "bobbyFoster137", password: "password144" },
  { email: "clara1@example.com", name: "Clara Edwards", username: "claraEdwards138", password: "password145" },
  { email: "derek1@example.com", name: "Derek Nelson", username: "derekNelson139", password: "password146" },
  { email: "elena1@example.com", name: "Elena Gray", username: "elenaGray140", password: "password147" },
  { email: "frank1@example.com", name: "Frank Wilson", username: "frankWilson141", password: "password148" },
  { email: "gracie1@example.com", name: "Gracie Walker", username: "gracieWalker142", password: "password149" },
  { email: "hugo1@example.com", name: "Hugo Young", username: "hugoYoung143", password: "password150" },
  { email: "indigo1@example.com", name: "Indigo Brooks", username: "indigoBrooks144", password: "password151" },
  { email: "julius1@example.com", name: "Julius Turner", username: "juliusTurner145", password: "password152" },
  { email: "kelsey1@example.com", name: "Kelsey Ross", username: "kelseyRoss146", password: "password153" },
  { email: "lance1@example.com", name: "Lance Hall", username: "lanceHall147", password: "password154" },
  { email: "maia1@example.com", name: "Maia Mitchell", username: "maiaMitchell148", password: "password155" },
  { email: "nikki1@example.com", name: "Nikki Collins", username: "nikkiCollins149", password: "password156" },
  { email: "oliver1@example.com", name: "Oliver Thompson", username: "oliverThompson150", password: "password157" },
  { email: "poppy1@example.com", name: "Poppy Hughes", username: "poppyHughes151", password: "password158" },
  { email: "quincy1@example.com", name: "Quincy Johnson", username: "quincyJohnson152", password: "password159" },
  { email: "rosie1@example.com", name: "Rosie Lee", username: "rosieLee153", password: "password160" },
  { email: "sophia1@example.com", name: "Sophia Evans", username: "sophiaEvans154", password: "password161" },
  { email: "travis1@example.com", name: "Travis Davis", username: "travisDavis155", password: "password162" },
  { email: "ursula2@example.com", name: "Ursula Scott", username: "ursulaScott156", password: "password163" },
  { email: "vincent1@example.com", name: "Vincent Taylor", username: "vincentTaylor157", password: "password164" },
  { email: "willow1@example.com", name: "Willow White", username: "willowWhite158", password: "password165" },
  { email: "xena3@example.com", name: "Xena Rivera", username: "xenaRivera159", password: "password166" },
  { email: "yasmine2@example.com", name: "Yasmine Jones", username: "yasmineJones160", password: "password167" },
  { email: "zachary2@example.com", name: "Zachary Evans", username: "zacharyEvans161", password: "password168" },
  { email: "angelina1@example.com", name: "Angelina White", username: "angelinaWhite162", password: "password169" },
  { email: "baxter1@example.com", name: "Baxter Young", username: "baxterYoung163", password: "password170" },
  { email: "candace1@example.com", name: "Candace Davis", username: "candaceDavis164", password: "password171" },
  { email: "derek1@example.com", name: "Derek Taylor", username: "derekTaylor165", password: "password172" },
  { email: "evan1@example.com", name: "Evan Harris", username: "evanHarris166", password: "password173" },
  { email: "florence1@example.com", name: "Florence Wright", username: "florenceWright167", password: "password174" },
  { email: "gwen2@example.com", name: "Gwen Carter", username: "gwenCarter168", password: "password175" },
  { email: "henry1@example.com", name: "Henry Murphy", username: "henryMurphy169", password: "password176" },
  { email: "isabella1@example.com", name: "Isabella Wilson", username: "isabellaWilson170", password: "password177" },
  { email: "jackson1@example.com", name: "Jackson Lopez", username: "jacksonLopez171", password: "password178" },
  { email: "kiana1@example.com", name: "Kiana Lee", username: "kianaLee172", password: "password179" },
  { email: "larissa1@example.com", name: "Larissa Johnson", username: "larissaJohnson173", password: "password180" },
  { email: "mira1@example.com", name: "Mira Gonzalez", username: "miraGonzalez174", password: "password181" },
  { email: "natalia1@example.com", name: "Natalia Harris", username: "nataliaHarris175", password: "password182"},
  { email: "olga1@example.com", name: "Olga Brown", username: "olgaBrown176", password: "password183" },
  { email: "paul1@example.com", name: "Paul Martin", username: "paulMartin177", password: "password184" },
  { email: "quinn1@example.com", name: "Quinn Harris", username: "quinnHarris178", password: "password185" },
  { email: "rebecca1@example.com", name: "Rebecca Adams", username: "rebeccaAdams179", password: "password186" },
  { email: "sasha1@example.com", name: "Sasha Thompson", username: "sashaThompson180", password: "password187" },
  { email: "troy1@example.com", name: "Troy Wright", username: "troyWright181", password: "password188" },
  { email: "ursula1@example.com", name: "Ursula Lopez", username: "ursulaLopez182", password: "password189" },
  { email: "vance1@example.com", name: "Vance Lewis", username: "vanceLewis183", password: "password190" },
  { email: "whitney1@example.com", name: "Whitney Brooks", username: "whitneyBrooks184", password: "password191" },
  { email: "xander1@example.com", name: "Xander White", username: "xanderWhite185", password: "password192" },
  { email: "yvette1@example.com", name: "Yvette Johnson", username: "yvetteJohnson186", password: "password193" },
  { email: "zoey1@example.com", name: "Zoey Miller", username: "zoeyMiller187", password: "password194" },
  { email: "alvin1@example.com", name: "Alvin Johnson", username: "alvinJohnson188", password: "password195" },
  { email: "brittany1@example.com", name: "Brittany Wilson", username: "brittanyWilson189", password: "password196" },
  { email: "caitlyn1@example.com", name: "Caitlyn Lewis", username: "caitlynLewis190", password: "password197" },
  { email: "daisy1@example.com", name: "Daisy Martin", username: "daisyMartin191", password: "password198" },
  { email: "elliot1@example.com", name: "Elliot Harris", username: "elliotHarris192", password: "password199" },
  { email: "fiona1@example.com", name: "Fiona Carter", username: "fionaCarter193", password: "password200" },
];

const requestUrl = "http://localhost:3000/api/auth";

function createAccount() {
  const len = userData.length;

  console.log("Length of data: "+len);
  userData.map(async (i) => {
    const res = await axios.post(requestUrl, {
      email: i.email,
      name: i.name,
      username: i.username,
      password: i.password,
    });

    if (res.data) {
      console.log(res.data.message);
    } else {
      // now it's throwing error
    }
  });
}

export { createAccount };
